"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [state, setState] = useState(0);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div>Layout : {state}</div>
        <button onClick={() => setState(state + 1)} className="p-1 bg-blue-800">
          Click
        </button>
        {children}
      </body>
    </html>
  );
}

